---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "my-replicaset"
  labels:
    purpose: learning
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - name: "nginx-port"
              containerPort: 80
              protocol: TCP


    
  